

# ["AppData/Local/Fonts"]
#     type = "archive"
#     url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
#     refreshPeriod = "168h"
#     format = "zip"
#     stripComponents = 1
