[color]
background = 'default'
foreground = '#82d3e2'

; gradient = 0
gradient = 1
gradient_color_1 = '#004e59'
gradient_color_2 = '#82d3e2'
gradient_color_3 = '#9eefff'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#004e59'
horizontal_gradient_color_2 = '#82d3e2'
horizontal_gradient_color_3 = '#9eefff'
horizontal_gradient_color_4 = '#82d3e2'
horizontal_gradient_color_5 = '#004e59'


